create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  "sortOrder" integer not null default 0
);

create table if not exists public.time_slots (
  id bigint generated by default as identity primary key,
  name text not null unique,
  "sortOrder" integer not null default 0
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  name text not null,
  "isActive" boolean not null default true,
  "sortOrder" integer not null default 0
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  "timeSlot" text not null,
  "isActive" boolean not null default true,
  "sortOrder" integer not null default 0
);

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  date text not null,
  "taskId" text not null,
  "staffId" text not null,
  "taskName" text,
  "staffName" text,
  timestamp text not null
);

create table if not exists public.temperature_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  type text not null,
  location text not null,
  temperature numeric not null,
  "staffId" text not null,
  "staffName" text,
  timestamp text not null
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null
);

create index if not exists idx_staff_active_name on public.staff ("isActive", name);
create index if not exists idx_tasks_active on public.tasks ("isActive");
create index if not exists idx_logs_date on public.logs (date);
create index if not exists idx_logs_task_date on public.logs ("taskId", date);
create index if not exists idx_temperature_logs_date on public.temperature_logs (date);

insert into public.app_settings (key, value)
values
  ('admin_pin', '5897'),
  ('timezone', 'Asia/Singapore'),
  ('shift_ended', 'false'),
  ('shift_closed_by', ''),
  ('shift_closed_at', '')
on conflict (key) do nothing;

alter table public.categories enable row level security;
alter table public.time_slots enable row level security;
alter table public.staff enable row level security;
alter table public.tasks enable row level security;
alter table public.logs enable row level security;
alter table public.temperature_logs enable row level security;
alter table public.app_settings enable row level security;

do $$
declare
  tbl text;
begin
  foreach tbl in array array[
    'categories',
    'time_slots',
    'staff',
    'tasks',
    'logs',
    'temperature_logs',
    'app_settings'
  ] loop
    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = tbl
        and policyname = 'allow_anon_all_' || tbl
    ) then
      execute format(
        'create policy %I on public.%I for all to anon using (true) with check (true)',
        'allow_anon_all_' || tbl,
        tbl
      );
    end if;

    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = tbl
        and policyname = 'allow_authenticated_all_' || tbl
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (true) with check (true)',
        'allow_authenticated_all_' || tbl,
        tbl
      );
    end if;
  end loop;
end $$;
