create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.time_slots (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  name text not null,
  "isActive" boolean not null default true
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  "timeSlot" text not null,
  "isActive" boolean not null default true
);

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  date text not null,
  "taskId" text not null,
  "staffId" text not null,
  "taskName" text,
  "staffName" text,
  timestamp text not null
);

create table if not exists public.temperature_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  type text not null,
  location text not null,
  temperature numeric not null,
  "staffId" text not null,
  "staffName" text,
  timestamp text not null
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null
);

create index if not exists idx_staff_active_name on public.staff ("isActive", name);
create index if not exists idx_tasks_active on public.tasks ("isActive");
create index if not exists idx_logs_date on public.logs (date);
create index if not exists idx_logs_task_date on public.logs ("taskId", date);
create index if not exists idx_temperature_logs_date on public.temperature_logs (date);

insert into public.app_settings (key, value)
values
  ('admin_pin', '5897'),
  ('timezone', 'Asia/Singapore'),
  ('shift_ended', 'false'),
  ('shift_closed_by', ''),
  ('shift_closed_at', '')
on conflict (key) do nothing;
