drop extension if exists "pg_net";


  create table "public"."notification_emails" (
    "id" bigint generated by default as identity not null,
    "email" text not null,
    "isActive" boolean not null default true
      );


alter table "public"."notification_emails" enable row level security;

CREATE UNIQUE INDEX notification_emails_email_key ON public.notification_emails USING btree (email);

CREATE UNIQUE INDEX notification_emails_pkey ON public.notification_emails USING btree (id);

alter table "public"."notification_emails" add constraint "notification_emails_pkey" PRIMARY KEY using index "notification_emails_pkey";

alter table "public"."notification_emails" add constraint "notification_emails_email_key" UNIQUE using index "notification_emails_email_key";

grant delete on table "public"."notification_emails" to "anon";

grant insert on table "public"."notification_emails" to "anon";

grant references on table "public"."notification_emails" to "anon";

grant select on table "public"."notification_emails" to "anon";

grant trigger on table "public"."notification_emails" to "anon";

grant truncate on table "public"."notification_emails" to "anon";

grant update on table "public"."notification_emails" to "anon";

grant delete on table "public"."notification_emails" to "authenticated";

grant insert on table "public"."notification_emails" to "authenticated";

grant references on table "public"."notification_emails" to "authenticated";

grant select on table "public"."notification_emails" to "authenticated";

grant trigger on table "public"."notification_emails" to "authenticated";

grant truncate on table "public"."notification_emails" to "authenticated";

grant update on table "public"."notification_emails" to "authenticated";

grant delete on table "public"."notification_emails" to "service_role";

grant insert on table "public"."notification_emails" to "service_role";

grant references on table "public"."notification_emails" to "service_role";

grant select on table "public"."notification_emails" to "service_role";

grant trigger on table "public"."notification_emails" to "service_role";

grant truncate on table "public"."notification_emails" to "service_role";

grant update on table "public"."notification_emails" to "service_role";


  create policy "allow_anon_all_notification_emails"
  on "public"."notification_emails"
  as permissive
  for all
  to anon
using (true)
with check (true);



  create policy "allow_authenticated_all_notification_emails"
  on "public"."notification_emails"
  as permissive
  for all
  to authenticated
using (true)
with check (true);



